language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install codecov
- pip install Sphinx==3.0.3
- pip install sphinx_rtd_theme==0.4.3
script:
- tox
after_success:
- codecov
- cd docs
- sphinx-apidoc ../split_dataset -o source
- make html
- cd ..
deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token:
        secure: PNll8Z+1R7L2ScWYP5nLJdnl+12Pk96Krw2HoKOOOEZiUrIfTCod9zgsweZslECei1WcYex5Y8QN8T5Bw3TwiBSjAX0U7WfW+wdY/8ywbfjq+SAT6/dHT126Kbq3S8U8ZUKpCYu9Esu3sss+Bo4rvIMI4LugxR7s6KtjIevJm5bHbgrTkv8x4ifGiYHfaQZqNMToLzpFkYlOY/JV5AnI3nyDyfjC9REG/NS3EqDAC6d0fRnBDkgMcGfH/g22tevhSoFec2OQlGHQrNAz/5PUT8qWzWLKVvlk2txtkYLpy1IKpUW3OZszShmr8E3E9n1sBtmKBdwS5+D7sAxNPGeMVniwZyuJa0Z5dRqsqRr86+yshys0JIO9k5x0VbYzG/RKPCyMVdhf4hyEjHoN0V2oAazGN9rRITJPTUBLKTADZWeRJz6nesvnWlmEcnc1fvp3KYi0L6k26PgXJa5DHHbbumqWJL6AVq0u2m+CeEpGUpUN44Yi/1Tzu5k6rb4OhPrzqMme9zYvVlvhzoTAHz+CXnVPX4V1z5l0c8icMF5zul3UMINLR75ItQ3/BOUv1X1XTk8FuIlvBv6BX+PlFrPfTMJwBjYEc/jv8GRbtc4l4ej+PBYWPHIU9PTrgCWfVimjf04KRdHJKmfKMr6l1ZdXAMRco9G7BCu6Vw+wIvOr+X0=
    on:
      tags: false
      branch: master
      python: 3.8
    local-dir: docs/_build/html
    committer-from-gh: true
  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    user: __token__
    password:
      secure: 4Om4fLif+gfVoYYm86uqdCKXSrDojq50XcSA4cLUmtz+mbugp9ewTbucYPHLqWm7LJw/0QixgstD8ivcFKwGXMh1K8vLG80ptOksVKkC2N7kznt+Mx1Kw57ryUmu+PGKb52iKeXDsNiLJcjPjvl9v1E2SA7iCvsP0ClV+n8+dsiXatoftsE9IB18ZbEGGrp8Wq6F2bgS/QQVvCx4MUXV5vJJxYlTnx9TZv1t8kcTtvt6fKT12vzImq6hLpooNInr9GHPm6zQk9+6ibCfSuWD8wFJfi60yiJxAmWhyc7mFc2UtuIVac34E0FAQPT0PGDXZnB+xqTGNJD/3CKkI+AwCO3QaUV6w4vLlNAcZUaAYl/ZPkCOsGIBJ4QVt25vJE9/qFJ2yAzjFJSUDoszztwvogcDwq0kGFMUGC3w4Wkqesqq2FtDQ7deKxO0vKeOFkP40uzPuUtEWVoJ3fRr66WyA+Br0EhhWRudaTlN/MSTK+SgwgFwmz8iiLBvL7BOHoPefDwgK0Z4G+692M8mLgwaOgEkztelFpL6YWH7IirbT2xzESMnJ8yQ7x+AOm1QZocdrZac3trfckMQUIzQgc+o/Ycsh+bwFE88GZdbC8+x1nlI7VkhoMHfPmRJgzXwDYk31ttKFmhTOKCxa6LqwpS15WAyPNFeFx4OArzGxVhnTXc=
    on:
      tags: false
      branch: master
      python: 3.8
    skip_existing: true
